export const LOAD_FETCHING ="LOAD_FETCHING";
export const LOGGING_OUT ="LOGGING_OUT";
export const SET_CURRENT_USER ="SET_CURRENT_USER";
export const LOGIN_FAILURE ="LOGIN_FAILURE";
export const IS_LOADING = "IS_LOADING";

export const LOAD_PAGES ="LOAD_PAGES";
export const LOAD_PRODUCTS ="LOAD_PRODUCTS";
export const LOAD_USERS ="LOAD_USERS";
export const LOAD_ORDERS ="LOAD_ORDERS";
export const LOAD_MESSAGES ="LOAD_MESSAGES";
export const LOAD_PLACES ="LOAD_PLACES";
export const LOAD_BANKS ="LOAD_BANKS";

export const GET_TOTAL_PAGES ="GET_TOTAL_PAGES";
export const GET_TOTAL_PRODUCTS ="GET_TOTAL_PRODUCTS";
export const GET_TOTAL_ORDERS ="GET_TOTAL_ORDERS";
export const GET_TOTAL_USERS ="GET_TOTAL_USERS";
export const GET_TOTAL_PLACES ="GET_TOTAL_PLACES";
export const GET_TOTAL_MESSAGES ="GET_TOTAL_MESSAGES";
export const GET_TOTAL_BANKS ="GET_TOTAL_BANKS";



